### ISSUE TITLE
Link to the pre-publication manuscript no longer working

### ISSUE THREAD

**Issue by christian-cahig** [TDPF/TDPF#2]

**Comment by stephen-frank** [comment]
Thanks for pointing that out. I've updated the link. The link takes you to my Zotero profile; scroll down and there is a spot to download the paper.

**Comment by christian-cahig** [comment]
@stephen-frank thank you very much.

As a side note, I just realized that you were one of the authors of _An introduction to optimal power flow: Theory, formulation, and examples_ (which I have been referring to as "Frank and Rebennack" in the OPF fundamentals). That has helped me a lot, and I always recommend it to my friends who want to learn about power system modelling, power flow equations, and OPF.

**Comment by stephen-frank** [comment]
That's great to hear! We wrote it because we thought such a paper needed to exist, so it's good to hear it has been useful. Even though my career went an entirely different direction after that work. :)

**Comment by jsexauer** [comment]
Yes thanks so much for sharing that, at the time we weren't sure how useful
that paper would turn out to be :)
